[build]
builder = "NIXPACKS"

[deploy]
startCommand = "python main.py"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production]
variables = { 
    PORT = "8000",
    RAILWAY_PUBLIC_DOMAIN = "https://nfl.critjecture.com",
    RAILWAY_ENVIRONMENT = "production"
}

# Add persistent volume for database
[[environments.production.volumes]]
mountPath = "/data"
source = "data-volume"
